export const Font = {
  PoppinsLight: 'Poppins-Light',
  PoppinsRegular: 'Poppins-Regular',
  PoppinsMedium: 'Poppins-Medium',
  PoppinsSemiBold: 'Poppins-SemiBold',
  PoppinsBold: 'Poppins-Bold',
  PoppinsExtraBold: 'Poppins-ExtraBold',
  PoppinsBlack: 'Poppins-Black',
  MontserratRegular: 'Montserrat-Regular',
  MontserratMedium: 'Montserrat-Medium',
  MontserratSemiBold: 'Montserrat-SemiBold',
  MontserratBold: 'Montserrat-Bold',
  MontserratExtraBold: 'Montserrat-ExtraBold',
  SourceSansProSemiBold: 'SourceSansPro-SemiBold',
  112: 'ITC Avant Garde Gothic LT Bold',
  Poppins300: 'Poppins-Light',
  Poppins400: 'Poppins-Regular',
  Poppins500: 'Poppins-Medium',
  Poppins600: 'Poppins-SemiBold',
  Poppins700: 'Poppins-Bold',
  Poppins800: 'Poppins-ExtraBold',
  Poppins900: 'Poppins-Black',
  impact: 'impact',
};
